###First Word Cloud
require(devtools)
install_github("lchiffon/wordcloud2")

Brand<-read.table("/home/Desktop/Data_Manipulation/BrandR.tsv", stringsAsFactors = F, header = T, sep = '\t')
names(Brand)
Brand2<-read.table("/home/Desktop/Data_Manipulation/BrandR2.tsv", stringsAsFactors = F, header = T, sep = '\t')
table(Brand$ADJ)
BA<-as.data.frame(table(Brand$ADJ))
names(BA)<-c("word","freq")
BA2<-as.data.frame(table(Brand2$ADJ))
names(BA2)<-c("word","freq")
table(Brand$SENTIMENT)
BS<-as.data.frame(table(Brand$SENTIMENT))
names(BS)<-c("word","freq")
require(wordcloud2)
head(demoFreq)
wordcloud2(demoFreq, size = 1.6)
wordcloud2(BA, size = .5, color = 'random-light', backgroundColor = 'black')
wordcloud2(BS, size = .5, color = 'random-light', backgroundColor = 'black')

setwd("/home/Desktop/Data_Manipulation")
letterCloud(BA, word = "R", size=.5)
figPath = system.file("examples/t.png",package = "wordcloud2")
wordcloud2(BA2, figPath = "/home/Desktop/Data_Manipulation/BowTie.png", size = .35, color = "black")
wordcloud2(BS, figPath = "/home/Desktop/Data_Manipulation/BowTie.png", size = .8, color = "skyblue")